# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('beds', 'Beds & mattressess'), ('furn', 'Furniture, wardrobes & shelves'), ('sofa', 'Sofas & armchairs'), ('table', 'Tables & chairs'), ('texti', 'Textiles'), ('deco', 'Decoration & mirrors'), ('light', 'Lighting'), ('cook', 'Cookware'), ('table', 'Tableware'), ('taps', 'Taps & sinks'), ('org', 'Organisers & storage accesories'), ('toys', 'Toys'), ('leis', 'Leisure'), ('safe', 'safety'), ('diy', 'Do-it-yourself'), ('floor', 'Flooring'), ('plant', 'Plants & gardering'), ('food', 'Food & beverages')], max_length=5),
        ),
    ]
