# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0002_auto_20180501_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('items', models.ManyToManyField(through='ykea.ItemQuantity', to='ykea.Item')),
            ],
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Shoppingcart'),
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Item'),
        ),
    ]
