# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='shoppingcart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ykea.Shoppingcart'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
