# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0006_auto_20180529_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='shoppingcart',
        ),
        migrations.AddField(
            model_name='clientcart',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ykea.Client'),
        ),
        migrations.AddField(
            model_name='clientcart',
            name='shoppingcart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Shoppingcart'),
        ),
    ]
